INSERT INTO Products(Product_desc,Product_category_id) VALUES ('איטריות',1)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('ביצים',1)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('בירה',1)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('גרגירי חומוס',1)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('דייאט ספרייט',1)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('דייאט קולה',1)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('חומוס',1)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('חומץ',1)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('חלה',1)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('יין',1)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('לחם קל',1)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('מלח',1)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('סודה',1)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('סוכר',1)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('עדשים',1)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('פסטה',1)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('קורנפלקס',1)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('קמח',1)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('ריבות',1)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('שמן',1)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('טחינה',1)

INSERT INTO Products(Product_desc,Product_category_id) VALUES ('אטבים',2)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('גומי לרצפה',2)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('יעה',2)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('כלים חד פעמיים',2)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('מברשות',2)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('מגבות נייר',2)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('מטטה',2)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('מפיות נייר',2)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('משחת נעליים',2)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('ניילון עטיפה',2)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('נייר טואלט',2)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('נרות שבת',2)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('סחבה',2)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('עיתון',2)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('שקיות אשפה',2)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('שקיות ניילון',2)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('שקיות קוקיז',2)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('שקיות קרח',2)

INSERT INTO Products(Product_desc,Product_category_id) VALUES ('בושם',3)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('גל שיער',3)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('דיאודורנט',3)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('מקלונים לאוזניים',3)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('משחת שיניים',3)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('סבון רחצה',3)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('סכיני גילוח',3)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('צבע שיער',3)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('צמר גפן',3)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('קונדישנר',3)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('קצב גילוח',3)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('שמפו',3)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('תחתוניות',3)

INSERT INTO Products(Product_desc,Product_category_id) VALUES ('אקונומיקה',4)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('מבריק למדיח',4)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('מוצרי גיהוץ',4)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('מלח למדיח',4)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('סבון למדיח',4)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('סבון לריצפה',4)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('ספריי לשירותים',4)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('פנטסטיק',4)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('רסס וכבס',4)

INSERT INTO Products(Product_desc,Product_category_id) VALUES ('גרונות',5)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('חזה עוף',5)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('חלקי עוף',5)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('כבד בקר',5)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('כבד עוף',5)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('כנפיים',5)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('כתף(לחמין)',5)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('נקניקיות',5)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('סטייקים',5)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('עצמות',5)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('בשר בקר',5)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('פסטרמה',5)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('שישליק',5)

INSERT INTO Products(Product_desc,Product_category_id) VALUES ('אקטימל',6)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('גבינה צהובה',6)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('חלב 1%',6)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('חלב 3%',6)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('סימפוניה 5%',6)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('פריגורט 0%',6)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('צפתית 5%',6)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('קוטג 5%',6)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('שמנת חמוצה',6)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('שמנת מתוקה',6)


INSERT INTO Products(Product_desc,Product_category_id) VALUES ('אספרגוס',7)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('זיתים',7)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('זיתים בלי חרצן',7)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('חמוצים',7)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('חמוצים',7)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('טונה (שמן)',7)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('לבבות דקל',7)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('מלפפונים חמוצים',7)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('עגבניות חתוכות',7)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('עגבניות שלמות',7)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('פטריות שלמות',7)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('פיטריות חתוכות',7)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('רסק עגבניות',7)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('תירס',7)

INSERT INTO Products(Product_desc,Product_category_id) VALUES ('בצל ירוק',8)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('בצל אדום',8)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('בזיליקום',8)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('ברוקולי',8)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('ברוקולי',8)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('גזר',8)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('דלעת',8)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('חסה',8)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('חצילים',8)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('מלפפונים',8)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('סלק אדום',8)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('סלק ירוק',8)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('סלרי',8)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('עגבניות',8)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('פטרוזיליה',8)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('פיטריות',8)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('פלפלים',8)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('קולורורבי',8)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('קוסברה',8)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('קישואים',8)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('שום',8)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('שומר',8)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('שעועית ירוקה',8)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('תפוח אדמה אדום',8)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('תירס',8)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('תפוחי אדמה',8)


INSERT INTO Products(Product_desc,Product_category_id) VALUES ('אגסים',9)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('אפרסקים',9)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('אשכוליות',9)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('בננות',9)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('דובדובנים',9)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('לימונים',9)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('מנגו',9)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('משמשים',9)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('נקטרינות',9)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('ענבים',9)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('קיווי',9)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('קלמנטינות',9)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('שזיפים',9)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('תפוזים',9)
INSERT INTO Products(Product_desc,Product_category_id) VALUES ('תפוחים',9)





